haproxytech/kubernetes-ingress

- deploy/haproxy-ingress.yaml
Fixes install. Without a ConfigMap defined, Ingresses are not detected.
> Added default ConfigMap to install yaml

- documentation/README.md
check documentation was referring 'load-balance' related information
> README: copy/paste typo in 'check' documentation

- controller-rate-limiting.go
- controller-requests.go
In the rate-limit feature, the tracking is done through tcp-request
rules.
That said, when the configuration is generated, those rules are missing.
This patch fixes this issue.
> BUG/MAJOR: rate-limit: missing track rule

- controller-misc.go
- controller.go
- documentation/README.md
- fs/etc/haproxy/global.cfg
These two commits make it possible to enable HAProxy logging via syslog-server annotation.
> Support logging via syslog-server annotation

- deploy/haproxy-ingress.yaml
Default SSL certificate should not be enabled by default: it enables SSL redirect which gives errors when the secret is not there (very common setup, since a lot of people make use of cert-manager and don't have default certificate).
> MINOR: do not set default-ssl-certificate by default

- controller-annotations.go
- controller-backend-update.go
- controller-haproxy.go
- controller.go
This is a code cleanup in handlePath, handleService and handleBackendAnnotations.
This separates the backend annotations logic from handleService.
It also separates updating backend from handling annotations. Which makes it easier to add more annotations for the backend configuration.
> Code cleanup 

- controller.go
Check the returned error form ServerVersion call at startup.
This way we can abort and log the error if there is any issue with the
server API. Otherwise the controller will segfault.
> MINOR Abort if the controller is not able to get the k8s server version

- controller-api.go
Transaction should be deleted if there are no changes otherwise this
will result in memory leak because parsers are not freed.
> BUG/MEDIUM: Delete transaction when there are no changes

- controller-https.go
In some cases there is no newline written between the key and the certificate
bundle. This results in the line being mangled and a parse error upon initialization:
-----END RSA PRIVATE KEY----------BEGIN CERTIFICATE-----
This patch always writes a newline to ensure the key and certificate bundle can be correctly loaded.
> BUG/MAJOR: Force writing a newline in PEM certificate bundle

- deploy/haproxy-ingress-deamonset.yaml
Related to my last pull request [Link](https://github.com/haproxytech/kubernetes-ingress/pull/129)
I create a new deploy strategy with DaemonSet of kubernetes to improve reliability and auto scaling by adding new kubernetes node. 
> I think ingress container should be deployed as DaemonSet to be work distributed and scalable, if you use Deployment you should set replica manually and add some attribute for pod anti-affinity to distribute all replicas on all workers but I think DaemonSet is a better option for automatic scaling. and DaemonSet let us to use hostPort to expose HTTP over port 80 and HTTPS over port 443 and we aren`t limit to use port number from 30000 range.
> BUILD: deployed as DaemonSet with hostPort to improve relaiability

- controller/annotations.go
- controller/configuration.go
- controller/events.go
- controller/haproxy.go
- controller/utils/flags.go
In addition to strictly matching ingress.class, controller will dynamically
drop or take into account ingress objects depending on their
ingress.class annotation.
> BUG/MEDIUM: Process only ingress objects which ingress.class strictly matches the controller --ingress.class CLI arg.

- controller/api.go
- controller/configuration.go
- controller/controller.go
- controller/frontend-annotations.go
- controller/requests.go
- documentation/README.md
Fixes #79.
Duplicates the mechanism for `request-set-header` to set response headers, also renamed the `FrontendHTTPRules` map for clarity.
I've tested that the functionality behaves as intended at least in terms of setting headers for the appropriate hostnames given ingress annotations or configmap entries. A pre-built image is available publicly on Dockerhub at [`easkay/haproxy-ingress:response_set_header`](https://hub.docker.com/repository/docker/easkay/kubernetes-ingress).
Thanks in advance for your time, and feedback is much appreciated.
> FEATURE/MEDIUM: Add response-set-header config

- controller/configuration.go
- controller/monitor.go
- controller/utils/flags.go
- documentation/controller.md
- main.go
Closes #182.
Implementing as CLI flag: `--sync-period=1s`: allowed time unit are the ones provided by Go's `time.Duration` package.
The default value is still set at `5s`, so no breaking change is expected.
In the case of non-well-formed unit, `flag.Parse` exits with code `1` and following error:
```
2020/04/27 08:10:21 invalid argument for flag `--sync-period' (expected time.Duration): time: unknown unit typo in duration 1typo
```
> Providing sync-period as CLI flag

- controller/frontend-annotations.go
Similarly to: https://github.com/haproxytech/kubernetes-ingress/commit/aac95d5fef1377b26df9cde6d49efeb0b5a13001
> MINOR: Ignore the port part when matching for HTTP redirects

- fs/etc/haproxy/haproxy.cfg
Closes #205.
Since HTX is the defacto mode, we can drop this option.
> MINOR: remove deprecated "http-use-htx" from stats section

- controller/kubernetes.go
- controller/monitor.go
- controller/utils/flags.go
- documentation/controller.md
- main.go
Closes #216.
Providing the new flag/annotation `--shared-informer-resync-period` with the default value set to 1 minute to make it backward compatible.
Documentation updated, tested locally on my _Kubernetes in Docker_ instance: please, review.
> Making Kubernetes Shared Informer resync period configurable via CLI

- main.go
Closes #220: as said there, a little typo.
> Fixing logs referencing to the default TLS certificate

- deploy/haproxy-ingress-daemonset.yaml
- deploy/haproxy-ingress.yaml
Apparently, a double declaration of the extensions API-group made it into both the daemonset as well as the deployment example.
I have taken the liberty to suggest the removal of the latter.
In any case, thank you very much for developing the haproxy ingress-controller and making your efforts available to the public. Cheers!
> remove doubles from rbac role

- controller/kubernetes.go
- controller/store/convert.go
- controller/store/events.go
- controller/store/types-equal.go
- controller/store/types.go
- deploy/kind/config/3.rbac.yaml
This PR should fix the CI, ignoring the missing `IngressClass` resource on clusters running version < 1.19.
> CI: supporting networking.k8s.io Ingress API group

- .github/workflows/kind.yaml
- .github/workflows/lint.yaml
The KinD GH Action is using the `core.addpath` method that [has been deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
Using the [0.5.0 release](https://github.com/engineerd/setup-kind/releases/tag/v0.5.0) should prevent future issues.
> Upgrading KinD GitHub Action due to deprecation path

- controller/configuration.go
I thought I would give master a go to see if it was affected by this issue. I confirmed that certs fail to issue without this change.
The path expressions are case sensitive and fail to match where the ingress has uppercase characters in the request paths. This leaves the path unchanged allowing a correctly cased ingress path to match.
Fixes #251 (on master)
> Remove lowercasing on path

- controller/requests.go
- fs/etc/haproxy/haproxy.cfg
The path expressions are case sensitive and fail to match where the ingress has uppercase characters in the request paths. This leaves the path unchanged allowing a correctly cased ingress path to match.
Fixes #251
> Remove lowercasing on paths

- controller/ingress/endpoints.go
`externalName` services are handled separately and has a single server generated. The `v1.4` branch had this check that appears to have been removed during various refactors. I have tested a custom image with this scenerio and the issue in #261 is no longer present.
In addition to the superfluous reloads, the `externalName` service had an ever growing list of servers appended to the configuration on every reload. This is no longer happening.
> Prevent aligning of backends for externalName services

- documentation/doc.yaml
- Replaced `<pre>` tags with Markdown code blocks. Put code keyword backticks around some keywords. 
- Improved grammar in a few descriptions. 
- Changed the `auth-secret` definition so that the description of the values is under the values key instead of the description key. This makes the table where we show the description only more succinct. 
- For `auth-type` and `auth-secret`, the example now shows both of these keys together because they are dependant upon one another.
> DOC/MEDIUM: Documentation formatting

- controller/controller.go
Hi,
I'm not really sure about this MR..
It adds dual-stack to the stats fronted. However, as-is, it won't obbey to --disable-ipv6 args (who would ever use those anyways ? :P)
Without binding on v6, the stats frontend doesn't work on v6-only clusters,
Let me know what you think.
Cheers !
> BUG/MEDIUM: stats frontend: listen IPv6 too

- controller/controller.go
Hi,
There was a bug in the `healthz` frontend that made it listen on IPv4 only
(i.e. `*:1042`, which is implicitly `0.0.0.0:1042`).
This made the liveliness probe fail on v6 only clusters as the endpoint
was not listening on IPv6:
```
frontend healthz
mode http
bind *:1042 name v4
monitor-uri /healthz
option dontlog-normal
```
which translates into the following socket:
```
tcp        0      0 0.0.0.0:1042            0.0.0.0:*               LISTEN
```
This commits adds another IPv6 bind on the frontend only if the
`--disable-ipv6` param is not set:
```
frontend healthz
mode http
bind 0.0.0.0:1042 name v4
bind :::1042 name v6 v4v6
monitor-uri /healthz
option dontlog-normal
```
which translates to:
```
tcp        0      0 0.0.0.0:1042            0.0.0.0:*               LISTEN
tcp        0 …
```
> BUG/MINOR: healthz: listen on IPv6 too

- documentation/README.md
- documentation/controller.md
- documentation/doc.yaml
Reading the `auth-secret` section I found that "password" and "omitted" were misspelled. Here are the corrections for those, some other spelling errors I found, and some misbehaving formatting too.
> DOC/MINOR: spell check docs and remove excess spacing

- controller/store/events.go
Currently, if the controller is started without the main ConfigMap existing, but it's added while the controller is running, the running HAProxy config isn't updated, because it's only rebuilt as a result of 'modified' or 'deleted' events, not 'added' events.
> Update config on ConfigMap added event

- documentation/README.md
- documentation/doc.yaml
Makes the example for `backend-config-snippet` apply to ConfigMap, Ingress and Service. Currently, it applies only to Service.
Note: I had to add some extra whitespace in front of the lines or else it does not render with the correct spacing on haproxy.com/documentation.
> DOC: Generalizes the 'backend-config-snippet' example

- build/Dockerfile
Stop hardcoding GOOS and GOARCH while building target IC binary, as we need Go
compiler to detect target arch properly.  Also revert to dumb-init from distro
for simpler multiarch images.
> BUILD: docker: Remove GOOS and GOARCH and use dumb-init from distro

- .github/workflows/docker_auto_release.yml
- .github/workflows/docker_manual_release.yml
Remove linux/ppc64le build target, as HAProxy Alpine linux/ppc64le builds are quite wobbly and have removed as a target.
> BUILD: docker: Remove linux/ppc64le target

- controller/annotations/backendCookie.go
When using `haproxy.org/cookie-persistence`, the controller inserts in backend section the `cookie` keyword:
```text
backend com-example-polygon-http
mode http
balance roundrobin
cookie SERVERID indirect nocache insert
server SRV_1 10.42.3.168:8888 check weight 128 cookie SRV_1
server SRV_2 10.42.4.134:8888 check weight 128 cookie SRV_2
```
But, when this annotation is removed from an existing Ingress or Service, the update process is incomplete and that directive is kept:
```text
backend com-example-polygon-http
mode http
balance roundrobin
cookie indirect nocache insert # <<<<< this line was left by mistake
server SRV_1 10.42.3.168:8888 check weight 128
server SRV_2 10.42.4.134:8888 check weight 128
```
This PR remove the `cookie` keyword if the annotation is no longer used.
> The `cookie` keyword is kept on backend after `haproxy.org/cookie-persistence` annotation is removed

- controller/handler.go
- controller/handler/tcp-services.go
TCP services always bind on IPv6 and IPv4 despite of `--disable-ipv6` and `--disable-ipv4` flags.
```text
frontend tcp-14031 
mode tcp
bind 172.31.10.8:14031 name v4
bind :::14031 name v6 v4v6  # !!!! this line shouldn't be here,
option tcplog
default_backend com-exemplo-echo-1025
```
This PR applies to `TCPServices` the same logic used on `HTTPBind` when creating frontends.
> TCP services listen on IPv6 even when passing --disable-ipv6

- controller/status/ingress.go
this passes the arguments through fmt.Sprintf to create meaningful log line. 
resolves https://github.com/haproxytech/kubernetes-ingress/issues/373
> FIX/SMALL: process template strings in "updating status of ingress..." log 

- controller/utils/utils.go
pod_name is expected to be:
Pod: `<DeploymentName>-<ReplicaSetName>-<RandomString>`
However, when the IC is ran externally the POD_NAME is usually "".
> BUG/MINOR: Prevent crash when POD_NAME is not correctly formatted

- .github/workflows/docker_nightly.yml
this action tries to create and push build even in forks
and that will not work due to credentials
> BUILD/MINOR: ci: build nightly images only on original repo

- .dockerignore
- build/Dockerfile
Hi,
This small MR adds 2 commits:
- Dockerignore: ignore some directories so that the `COPY / /src` cache step is preserved
- Warn when TARGETPLATFORM is not defined to make the `exit 1` error clearer
Thanks and cheers !
> Improve Dockerfile best practices

- controller/monitor.go
Since whitelisted namespaces were being appended anyways, the first entries in the
namespaces were all empty strings thus causing ingress controller to access
k8s resources on a cluster level unnecessary.
> Use slice instead of static sized arrays.

- controller/annotations/service/loadbalance.go
When using annotation for load balancing algorithm with parameters, the arguments were not parsed correctly for "hdr", "random" and "rdp-cookie" due to wrong regex.
This was mentioned in #104 and marked as fixed, but currently works only for url_param. 
What is the problem:
value := "hdr(test_header)"
tokens := strings.Split(value, " ")
reg := regexp.MustCompile("(\\(|\\))")
algorithmTokens := reg.Split(tokens[0], -1)
fmt.Println("Proposal:", algorithmTokens, "length:", len(algorithmTokens))
reg = regexp.MustCompile(`(\\(|\\))"`)
algorithmTokens = reg.Split(tokens[0], -1)
fmt.Println("Original:",algorithmTokens, "length:", len(algorithmTokens))
Output:
Proposal: [hdr test_header ] length: 3
Original: [hdr(test_header)] length: 1
> BUG/MINOR: Fix parsing for load balancing algorithm parameters

- controller/handler/https.go
Spotted when going through trace level logs on a Kubernetes cluster using this project.
> BUG/MINOR: Minor spelling mistake fix.

- fs/usr/local/etc/haproxy/haproxy.cfg
- pkg/controller/controller.go
- pkg/haproxy/api/api.go
- pkg/haproxy/api/frontend.go
- pkg/utils/flags.go
Currently, it is not possible to simultaneously run two **host-mode** ingress controllers on the same node, because the binds `127.0.0.1:10000` ([local peer](https://github.com/haproxytech/kubernetes-ingress/blob/9e4371177f86bc48c63e79c56968a4f459666ae4/fs/usr/local/etc/haproxy/haproxy.cfg#L17)), `*:1024` ([stats](https://github.com/haproxytech/kubernetes-ingress/blob/9e4371177f86bc48c63e79c56968a4f459666ae4/fs/usr/local/etc/haproxy/haproxy.cfg#L39)), and `0.0.0.0:1042` ([health](https://github.com/haproxytech/kubernetes-ingress/blob/9e4371177f86bc48c63e79c56968a4f459666ae4/fs/usr/local/etc/haproxy/haproxy.cfg#L32)) are hardcoded.
This PR allows using custom ports for local peer, stats and healthz.
Fixes #348
---
Considering some minor API changes between 1.7 and master, I backported this …
> MINOR: allow custom ports for local peer, stats and healthz

- pkg/annotations/global/syslogServer.go
Fixes #420
When using more than one syslog server, the algorithm for comparing log targets never succeeds, because the conversion of each `syslog-server` annotation's line into a `models.LogTarget` will always set the `.Index` field equal to 0:
https://github.com/haproxytech/kubernetes-ingress/blob/88a9cb4a106a084c93549909f9f862afeca4de85/pkg/annotations/global/syslogServer.go#L59
In this scenario, any state change causes a restart because `lg` and `newLg` will never be equal (either because of the slice order, or because of the different `.Index` fields):
https://github.com/haproxytech/kubernetes-ingress/blob/88a9cb4a106a084c93549909f9f862afeca4de85/pkg/controller/global.go#L84-L89
ConfigMap input:
```yaml
syslog-server: |
address:stdout, format:raw, facility:daemon, level:notice …
```
> BUG/MINOR: using more than one syslog server always leads to unnecessary restarts

- build/Dockerfile
This PR reorders image layers, copying binary last to favor caching and speed up the image build.
> MINOR: copies binary last, to favor caching and speed up the image build

- pkg/handler/https.go
After commit c954b4383865a0abd7eab3b3d77fe3ed45be29aa, if you don't use `client-ca`, the comparison between `BindParams.Verify` and `client-crt-optional` will never be true, which will force an unnecessary reload of the instance every 10 minutes (the value of `cache-resync-period`).
To make the bug easier to reproduce, reduce the `cache-resync-period` time to 20 seconds and create a controller without passing the `ca-file` annotation.
If `client-ca` and `client-crt-optional` aren't used, `BindParams.Verify` will always be an empty string and therefore can't be equal to `"required"`.
https://github.com/haproxytech/kubernetes-ingress/blob/3d8a6874e328b9cb0febae1040bc3f3b7eb4b0c3/pkg/handler/https.go#L110-L120
So, if `client-ca` and `BindParams.SslCafile` are equal and **both are empty**, we …
> BUG/MINOR: Prevents unnecessary reloading when the attribute `client-ca` is not used.

- pkg/handler/refresh.go
**Important**: To reproduce this bug, we first need to get away from bug #455. To do so, apply that patch or pass a `client-ca` certificate, otherwise, the reload will be triggered (but for other reasons explained in that PR).
If you delete an Ingress and the method `HAProxy.RefreshRules` doesn't trigger a reload, the backend will be kept on HAProxy.
To reproduce, create two or more ingresses with the same set of rules (`ssl-redirect: "true"`, for example, or no rules at all). Then delete one of them and see that the reload will not be triggered.
This was caused partially by commit 2f200cf43 `OPTIM: Enable dynamic update of HAProxy map files`. It disabled the update via reloads in favor of dynamic map update (which is great, by the way), but did not handle ingress deletion cases.
> BUG/MINOR: triggers a reload if an Ingress is deleted

- pkg/annotations/service/cookie.go
Fixes #459 
When a Service/Ingress/ConfigMap is configured with the annotation `cookie-persistence`, the comparison with the corresponding backend in the HAProxy settings will always fail, because the `backend.Cookie.Domain` attribute of an initialized model is a `<nil slice>` and the corresponding value returned by HAProxy is an empty array.
```text
service/service.go:134 Service 'exemplo/bazaar': backend 'exemplo_bazaar_http' updated: [Cookie.Domains: <nil slice> != []]
Reload required
```
> BUG/MINOR: Prevents unnecessary reloads when `cookie-persistence` is enabled.

- documentation/canary-deployment.md
Recent Kubernetes versions no longer offer version `networking.k8s.io/v1beta1` for `Ingress` objects. Update documentation to use `networking.k8s.io/v1` instead.
Signed-off-by: Ruben Laban <ruben@tun0.nl>
> DOC/MINOR: Upgrade Ingress API version in Canary example

- pkg/haproxy/env/defaults.go
When using a global CRD, every state change triggers a hard restart on HAProxy (even a simple pod scale):
```text
2022/08/03 16:20:49 DEBUG   global.go:81 Global config updated: [TuneOptions: <nil pointer> != models.GlobalTuneOptions]
Restart required
```
When synchronizing a `core.haproxy.org.Global` resource, the comparison with the corresponding settings in the HAProxy will always fail, because the `TuneOptions` attribute of an initialized `models.Global` is a `<nil pointer>` and the corresponding value returned by HAProxy is an empty `models.GlobalTuneOptions`.
This PR sets an empty `models.GlobalTuneOptions` as default value of `global.TuneOptions` attribute to prevent unnecessary restarts.
> BUG/MINOR: avoid hard restarts when using a Global CRD

- pkg/service/endpoints.go
the annotation `haproxy.org/cookie-persistence` is supposed to enable dynamic cookies for the backend, but i've found that it is still returning static cookies.
I tested with 1.7.9 and 1.8.0 and see the same behavior. If I define an ingress with the annotation
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test
namespace: test
annotations:
haproxy.org/cookie-persistence: "COOKIE"
```
The generated backend configuration looks like the following. Note the dynamic cookie option and key is set, but the server entries each specify a cookie (`SRV_1` and `SRV_2`). If cookies are present on the servers, it disables the dynamic mode.
```
backend test_app_http
mode http
balance roundrobin
option forwardfor
no option abortonclose
default-server check
cookie COOKIE dynamic …
```
> BUG/MINOR: don't add cookie to server if dynamic cookie enabled

- documentation/annotations.md
- documentation/doc.yaml
The `path-rewrite` annotation in the documentation was not displaying correctly. This fix changes the doc.yaml to use the `example_configmap` and `example_ingress` fields, which allow for a raw snippet example.
This fixes #510
> DOC/MINOR: Fixed formatting of path-rewrite in docs

- pkg/haproxy/process/interface.go
We use [load-server-state-from-file](http://cbonte.github.io/haproxy-dconv/2.6/configuration.html#load-server-state-from-file).
When these reloads occur (e.g. when an ingress is applied), we see the following logged:
```
config: Can't get version of the global server state file '/var/state/haproxy/global'.
```
When we dug deeper into server_state.c in HAProxy where this error is logged, we see the following
```
/* first character of first line of the file must contain the version of the export */
local_vsn = srv_state_get_version(f);
if (local_vsn == 0) {
ha_warning("Proxy '%s': Can't get version of the server state file '%s'.\n",
curproxy->id, file);
goto close_localfile;
}
```
When I exec into the pod, I confirmed that the first line of the `/var/state/haproxy/global` is an empty line. …
> BUG/MINOR: remove newline if present in server state file

- main.go
It might be a misunderstanding, but my expectation of `-v` is "print version _and exit_", which is currently not the case. Feel free to close if this is intended behavior.
> BUG/MINOR: quit after printing version when invoked with -v

- pkg/controller/builder.go
Wanted to add an alternative healthcheck endpoint like the PR https://github.com/haproxytech/kubernetes-ingress/pull/536 which wasn't got merged because the owner didn't reply.
I fixed the response header also.
Feel free to add remarks if something is missing.
> BUG/MEDIUM: support alternative healthcheck endpoint

- pkg/controller/controller.go
- pkg/ingress/ingress.go
- pkg/route/route.go
Fixes #567
All custom routes are stored in the `routes.CustomRoutes` map using the backend name as the key (`ServiceNS_ServiceName_PortName`). When we encounter two distinct IngressRules, whether they are within the same Ingress or not, and they utilize different hosts or paths while pointing to the same Service, they end up sharing the same key in `CustomRoutes`. This similarity in keys results in comparison failures during every synchronization, requiring a hard reload of HAProxy.
Rather than storing the custom routes in a map keyed by backend name, this PR stores all the resulting `use_backend` directives in a slice and compares them between syncs.
> BUG/MINOR: prevents clash on custom routes names to avoid unecessary restarts

- pkg/store/events.go
If the number of endpoints of a service reaches zero, the HAProxy will be restarted when this same service returns a non zero target set. This scenario happens, for example, during a deploy/rollout of a workload with `replicas: 1` or if the rolling strategy of the workload has `maxUnavailable: 100%`.
It is very easy to reproduce this bug:
```bash
k scale deployment whoami --replicas 5
k scale deployment whoami --replicas 1
k scale deployment whoami --replicas 0
k scale deployment whoami --replicas 1
```
When the number of endpoints reaches zero, the `ns.HAProxyRuntime[data.Service]` variable is recreated and the check `len(backend.HAProxySrvs) < srvSlots` causes a restart:
https://github.com/haproxytech/kubernetes-ingress/blob/886db237ced6fb5c2f9cc49fe645ec9155f6d5ff/pkg/service/endpoints. …
> BUG/MINOR: avoid hard restarts when the number of endpoints reaches zero

- deploy/tests/integration/base-suite.go
- deploy/tests/tnr/routeacl/suite_test.go
- fs/usr/local/etc/haproxy/haproxy.cfg
- pkg/controller/controller.go
This PR fixes #566.
Creates new binds (instead of editing them) of the `healthz` and `stats` frontends to avoid port conflicts at the first start of the HAProxy when using `hostNetwork: true`.
Since these bind directives are not required, the first start of HAProxy is not affected.
The `http` and `https` frontends were already being created before this PR.
> BUG/MINOR: prevents port conflicts on startup when using hostNetwork

- pkg/controller/global.go
Every check on Defaults CRD triggers a reload because `default` section name is hardcoded as `haproxytech`: https://github.com/haproxytech/kubernetes-ingress/blob/13fc60b9a52d746bbf7a05afd1ebde580739223b/pkg/haproxy/api/global.go#L33
Since the default section name is hardcoded as `haproxytech`, every event processed by the controller will trigger a hard reload, regardless of the `spec.name` value the user passes in the Defaults CRD (even if blank), because the comparison check will never pass (unless the user sets `spec.name` exactly to `haproxytech`).
> BUG/MINOR: prevents unnecessary reloads due to CRD defaults.name

- pkg/handler/prometheus.go
When the `--prometheus` flag is passed, the Prometheus backend check always fails if the controller namespace isn't `haproxy-controller`. Consequently, all events received by the controller trigger a reload of HAProxy.
```text
2024/03/09 12:32:14 INFO    instance/configuration.go:21 [transactionID=8a5a139f-1b65-4faf-8e40-dc467a54dcfb] reload required : creation/modification of prometheus endpoint
```
Since the backend name depends on the namespace, it shouldn't be hardcoded.
> BUG/MINOR: prevents unconditional reloads when prometheus is enabled and controller namespace isn't `haproxy-controller`

- documentation/annotations.md
- documentation/controller.md
- documentation/doc.yaml
ssl-redirect-port - in config map data everything is a stringso the number must be enclosed in quotes to be interpreted as string https-bind-port - the example was refererring to http-bind-port. probably copy-paste and forgot to update the name
> Update doc.yaml - https-bind-port and ssl-redirect-port fixes

- pkg/controller/global.go
This pull request is refering to https://github.com/haproxytech/kubernetes-ingress/issues/652
**CAREFUL**
I am absolutely not familiar with Go language (I'm a PHP guy). I tried to be very careful but please read my code carefully before accepting the commit.
**EXPLANATIONS**
I removed the unused `updated` variable and fixed the error message. I just used the same syntax as line 149.
I also used `%+v` to show field name (more explicit).
> MINOR: fix info message when global config is updated

- .github/workflows/.goreleaser.yml
- .github/workflows/actions.yml
- .github/workflows/docker_auto_release.yml
- .github/workflows/docker_description.yml
- .github/workflows/docker_manual_release.yml
- .github/workflows/docker_nightly.yml
This pull request updates the GitHub Actions to their latest versions, addressing existing warnings.
- Upgrade `actions/checkout` to v4
- Upgrade `actions/setup-go` to v5
- Upgrade `actions/cache` to v4
> BUILD/MINOR: ci: upgrade github actions

- deploy/haproxy-ingress-daemonset.yaml
- deploy/haproxy-ingress.yaml
mismatched from service object
Hey all - noticed when updating our deployment that nothing is being served on either port 443 or port 80 on the pod anymore. Figured I'd correct this to the current defaults.
Thanks!
> BUG: update IC pod-serving port to match default

- pkg/controller/controller.go
- pkg/controller/handler.go
- pkg/handler/http-bind.go
- pkg/utils/flags.go
We are currently using ingress controller as external mode, so it would be nice that we can control the thread pin on http/https/healthz for better performance.
The PR is adding those flag to support thread pin for ingress controller to set them on haproxy config.
i don't think its a necessary requirement in term of if the controller is running inside Kubernetes cluster, but it would be a great feature to provide for people running it as external mode.
> supporting thread pin on http https and healthz frontend

- pkg/controller/controller.go
- pkg/utils/flags.go
an addition to https://github.com/haproxytech/kubernetes-ingress/pull/661
i think i missed stats binding thread on that PR. this adds it
> MINOR: support thread pin on stats

- deploy/tests/e2e/client.go
- deploy/tests/e2e/map-updates/update_test.go
- pkg/controller/controller.go
- pkg/haproxy/main.go
- pkg/route/route.go
Fixes #703.
We introduce a new map `path-prefix-exact` which contains exact match patterns for ingress pathType `Prefix`. From now on the map `path-exact` will only contain patterns from pathType `Exact`. The generated HAProxy config will check `path-exact` first,  `path-prefix-exact` second and `path-prefix` third. That way pathType `Exact` always wins.
> BUG: Make ingress pathType "Exact" always override pathType "Prefix"
